"""Generate docs/ASSET_MANIFEST.md from the registry, and check that CREDITS.md and assets/licenses/README.md
(maintained by hand) credit every source pack."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from common import *  # noqa
from build_tiles import TERRAIN_TILES

load_registry()
R = REGISTRY
CREDITS = json.load(open(os.path.join(ROOT, "docs", "art", "pipeline", "credits.json"), encoding="utf-8"))
out = []
W = out.append


def keys(prefix, kind=None):
    return sorted(k for k, v in R.items() if k.startswith(prefix) and (kind is None or v.get("kind") == kind))


def rng(fr):
    fr = list(fr)
    if len(fr) == 1:
        return str(fr[0])
    if fr == list(range(fr[0], fr[-1] + 1)):
        return "%d-%d" % (fr[0], fr[-1])
    return ",".join(str(f) for f in fr)


def anims(v):
    items = sorted(v.get("anims", {}).items(), key=lambda kv: kv[1]["frames"][0])
    return "; ".join("**%s** %s @%s fps %s" % (n, rng(a["frames"]), a["fps"], "loop" if a["loop"] else "once") for n, a in items)


def sz(v):
    return "%dx%d" % tuple(v["size"])


def fr(v):
    return "%dx%d" % tuple(v["frame"])


def gr(v):
    return "%dx%d" % tuple(v["grid"])


def pv(v):
    return "(%d, %d)" % tuple(v["pivot"]) if "pivot" in v else "-"


def table(head, rows):
    W("| " + " | ".join(head) + " |")
    W("|" + "|".join("---" for _ in head) + "|")
    for r in rows:
        W("| " + " | ".join(str(c).replace("|", "/") for c in r) + " |")
    W("")


def short(k):
    return "`" + k[len("assets/"):] + "`"


def pal(rel, n=6):
    im = load(os.path.join(ROOT, *rel.split("/")))
    return " ".join("`%s`" % c for c, _ in palette(im, n))


# =============================================================================
W("# ASSET_MANIFEST - Club & Grub")
W("")
W("Reference for every file under `assets/`. Generated by `docs/art/pipeline/build_manifest.py` from the registry that the")
W("asset pipeline writes while it builds the files, so the numbers below are measured, not typed by hand.")
W("Sections 1-16 were generated for 1.0 and then edited by hand (the Brute re-pack in 5 and 14, the app icons in 12, the")
W("loudness tables of 13.4, a few notes): today the script reproduces 653 of their 749 lines, so carry those edits over")
W("before re-running it (`docs/THIRD_PARTY.md` 5). Section 17 (2.0) is written by")
W("`docs/art/expansion/pipeline/build_expansion.py`; section 18, the ledger with the source, author, licence and changes")
W("of every single file, by `tools/audit_assets.py --write-ledger` - the build runs that tool and fails on any gap.")
W("Proof screenshots composed only from these files: `docs/art/mock_jungle.png`, `mock_cave.png`, `mock_ice.png`,")
W("`mock_volcano.png`, `mock_feast.png`, `mock_boss_brute.png`, `mock_boss_colossus.png` (each 2560x1440 = base viewport x4).")
W("")
W("## 1. Art direction and global conventions")
W("")
W("**One artist, one look.** Hero, enemies, bosses, NPCs, all terrain, props, parallax layers, HUD, bitmap fonts and most FX come")
W("from a single purpose-made kit: *Superpowers Asset Packs - Prehistoric Platformer* by Pixel-boy / Sparklin Labs (CC0). It is")
W("chunky cartoon pixel art with a 2 px dark-brown outline (`#272018`), flat cel shading and a warm palette. Everything added from")
W("other packs was chosen or processed to sit inside that look (dark 2 px outline, flat shading): 16 px food / gem icons at")
W("integer 2x, 32 px giant food at 2x with an added `#272018` outline, carved-stone touch buttons at 2x recoloured to sandstone.")
W("")
table(["Setting", "Value"], [
    ["Base viewport", "**640 x 360 art px** (16:9) = **320 x 180 logical px** x `ART_SCALE` **2** (PHYSICS.md 15.3)"],
    ["Tile size", "**32 x 32 art px** = 16 x 16 logical px; 20 x 11.25 tiles visible (the original shows 20 x 11)"],
    ["Hero size", "body 44 x 56 art px (22 x 28 logical) = 15.6 % of the screen height, i.e. about 1/6 as in Prehistorik 2"],
    ["Integer window scales", "1280x720 = x2, 1920x1080 = x3, 2560x1440 = x4, 3840x2160 = x6"],
    ["Texture filter", "Nearest everywhere, no mipmaps, no texture compression artefacts (import PNGs lossless)"],
    ["Sheet layout", "uniform grid, frames numbered row-major from 0 (`frame = row * columns + column`), ready for `Sprite2D.hframes / vframes`"],
    ["Actor pivot", "**(cell_w / 2, cell_h - 16)** = the feet point of PHYSICS.md 2 (bottom-centre). `centered = false`, `offset = (-cell_w/2, -(cell_h-16))`; `flip_h` mirrors correctly because the pivot is horizontally centred. Bosses at 2x use `cell_h - 32`."],
    ["Facing", "every actor sheet faces **right**; exceptions: `bat` (front view) and `colossus` (faces left, lives in the right wall)"],
    ["Item / object / prop pivot", "bottom-centre of the cell unless the table says otherwise"],
    ["Collision boxes", "given in logical px around the feet point: `left = x - w/2`, `top = y - h` (PHYSICS.md 2.1 box test). They are suggestions measured from the art."],
    ["Pixel density", "native 1x of the anchor pack. Deliberate integer upscales (nearest neighbour): bosses 2x, 16 px icons 2x, giant food 2x, touch buttons 2x. Nothing is scaled by a non-integer factor."],
])
W("Why 640 x 360 and not 320x180 / 384x216 / 480x270: the chosen art is drawn at twice the density of 16 px-tile packs (hero 45x57 px,")
W("32 px terrain modules). At 640x360 it reproduces the original framing exactly (20 tile columns, hero 1/6 of the height); at 480x270 only")
W("15 x 8.4 tiles would fit and the hero would fill 21 % of the height. Game logic still runs in the original's 320x180 logical pixels:")
W("simulate in logical px and multiply positions by `ART_SCALE = 2` when placing sprites, exactly as PHYSICS.md 15.3 describes.")
W("")
W("File naming: lower_snake_case; `_b` = second palette of the same sheet layout; audio `_a.._d` = interchangeable variants.")
W("")

# ----------------------------------------------------------------------------- archetype mapping
W("## 2. GAMEPLAY.md archetype -> chosen sprite")
W("")
table(["Archetype (GAMEPLAY 5.2 / 12.2)", "Role", "Sprite sheet(s)", "Animations to use", "Suggested skins per world"], [
    ["0 Sky dropper", "Dropper", "`sprites/enemies/egg_kid.png` (+`_b`)", "fall = `roll` (egg), landing = `land`, then `walk`", "all worlds; `_b` palette for Expert"],
    ["2 Yo-yo dangler", "Dangler", "`sprites/enemies/bat.png` (+`_b`)", "`hang` (frame 13); draw the thread from the top centre of the sprite; `dead`", "cave, jungle canopy, ice cave (`_b`)"],
    ["3 Ceiling dropper -> chaser", "Lurker", "`sprites/enemies/insect.png` (+`_b`)", "`hang` while intangible, descend, then `walk` (chase)", "cave, volcano (`_b`)"],
    ["4 Pendulum", "Swinger", "`sprites/enemies/bat_b.png`", "`hang` rotated by the pendulum angle, or `swoop`", "cave, jungle"],
    ["5 Sentry diver", "Stinger", "`sprites/enemies/insect.png` / `insect_b.png`", "`fly` (hover and dive)", "jungle, volcano"],
    ["6 Clever flyer", "Harrier", "`sprites/enemies/pterodactyl.png` (+`_b`)", "`fly`; `screech` when it swoops", "jungle, ice (`_b`)"],
    ["7 Kamikaze diver", "Dart", "`sprites/enemies/pterodactyl_b.png`, `bat.png`", "`dive` (pterodactyl) / `swoop` (bat)", "ice, volcano"],
    ["8 Hopper", "Hopper", "`sprites/enemies/mini_rex.png` (+`_b`), `lizard_b.png`", "`idle` (pause), `walk` frame as jump pose / `hop`, `attack` on contact", "jungle (orange), ice (`_b` blue)"],
    ["9 Patroller, ground", "Walker", "`sprites/enemies/turtle.png` (+`_b`)", "`walk`; follows slopes", "all worlds"],
    ["9 Patroller, air", "Glider", "`sprites/enemies/bat.png`, `pterodactyl.png`", "`fly`", "cave / jungle"],
    ["10 Burrower", "Digger", "`sprites/enemies/lizard.png` (+`_b`)", "rise / sink = reveal the `idle` frame bottom-up with a clip rect, `hop` while walking", "cave, volcano; boss minions"],
    ["11 Arc leaper", "Leaper", "`sprites/enemies/dragon.png` (+`_b`)", "leap = `attack` frames 7-8 (stretched lunge), glide = `glide`", "volcano (purple), ice water pits (`_b` teal)"],
    ["12 Edge rusher", "Charger", "`sprites/enemies/rival.png`, `rex.png` (+`_b`)", "`walk` at 16-20 fps", "rival caveman everywhere; rex as heavy charger in worlds 3-4"],
    ["stationary hazard ('red snake')", "Snapper", "`sprites/enemies/plant.png` (+`_b`)", "`idle`, `windup` + `bite` when the hero is within 84 art px", "jungle, feast"],
    ["1 Decoration", "-", "`tiles/jungle/props/vine_a.png`, `vine_b.png`, `tiles/cave/props/critter_shadow.png`", "static", "-"],
    ["Boss: Brute (6.1)", "giant", "`sprites/bosses/brute.png`, `brute_enraged.png`", "`idle` (watch), `taunt` (chest beat), `jump` + `land`, `roll` (leap), `attack` (punch), `pound`, `hurt`, `death`", "level 2-2; `brute_enraged` when under 60 hit points or for the Expert rematch"],
    ["Boss: Wall Colossus (6.3)", "wall statue", "`sprites/bosses/colossus.png`", "`idle`, `spit` (rock), `slam` (ceiling drop cue), `hurt`, `rage`, `broken`", "level 4-2"],
    ["(stretch) Rooted Guardian (6.2)", "stationary puncher", "not built - reuse `plant.png` at 2x or `rex.png`", "-", "optional mid-boss of 4-1"],
    ["Tally companion (3.7)", "NPC", "`sprites/npc/companion.png`", "`idle`, `walk`, `hurt` (crying on game over)", "-"],
])

# ----------------------------------------------------------------------------- player
W("## 3. Player")
W("")
rows = []
for k in keys("assets/sprites/player/"):
    v = R[k]
    rows.append([short(k), sz(v), fr(v), gr(v), pv(v), v["facing"], v["note"]])
table(["File", "Size", "Frame", "Grid (cols x rows)", "Pivot", "Facing", "Note"], rows)
h = R["assets/sprites/player/hero.png"]
W("All four hero sheets share one layout; swap the texture when the weapon changes (`hero.png` = club, the default).")
W("Thrown weapons (axe, boomerang): the release frames show an empty hand - spawn `sprites/fx/projectile_<weapon>.png` there.")
W("")
table(["Animation", "Frames", "fps", "Loop", "Use"], [
    [n, rng(a["frames"]), a["fps"], "yes" if a["loop"] else "no", u] for n, a, u in [(n, h["anims"][n], u) for n, u in [
        ("idle", "standing, club on the shoulder"), ("walk", "walk and run (use 12 fps walking, 16 fps at full speed)"),
        ("jump", "rising; hold the last frame"), ("fall", "falling"), ("land", "landing squash after a long fall; also the skid pose"),
        ("crouch", "Down held (crouch box)"), ("crawl", "crawl shuffle (Down + direction)"), ("roll", "alternative crawl / long-fall tumble (ball)"),
        ("attack", "forward swing; frame 29 is the hit frame (slash arc drawn in)"), ("attack_up", "Up + attack, overhead strike; frame 32 hits"),
        ("attack_crouch", "Down + attack, low strike; frame 34 hits"), ("attack_air", "swing while airborne; frame 36 hits"),
        ("hurt", "thrown back (22 ticks)"), ("death", "death toss; 39-40 while airborne, 41-43 if you let him land"),
        ("climb", "ladders / vines (back view, optional mechanic)"), ("victory", "level complete, club raised"),
        ("glide", "hanging under `sprites/objects/glider.png`")]]])
W("Suggested collision boxes (logical px, w x h, centred on the feet point): stand / walk / jump **22 x 28**; crouch / crawl **24 x 22**;")
W("roll **18 x 18**. PHYSICS.md 2.1 lists the original's 32 x 35 and 40 x 30: keep those for a 1:1 feel test, the art fits inside them.")
W("Club reach in the hit frame: 44 logical px in front of the feet point, 8-30 px above the ground (the baked slash arc).")
W("")
W("Edits: " + h["edits"] + ".")
W("")

# ----------------------------------------------------------------------------- enemies / bosses / npc
def actor_section(title, prefix, kind, intro):
    W("## " + title)
    W("")
    W(intro)
    W("")
    ks = [k for k in keys(prefix) if R[k]["kind"] == kind]
    rows = []
    for k in ks:
        v = R[k]
        rows.append([short(k), sz(v), fr(v), gr(v), pv(v), v["facing"], ("%dx%d" % tuple(v["body_box_logical"])) if "body_box_logical" in v else "-", v.get("note", "")])
    table(["File", "Size", "Frame", "Grid", "Pivot", "Facing", "Body box (logical w x h)", "Role / notes"], rows)
    W("Animations (frame indices, fps, loop):")
    W("")
    for k in ks:
        v = R[k]
        base = k[:-4]
        if base.endswith("_b") and (base[:-2] + ".png") in R:
            continue
        twin = " (same for `%s`)" % (os.path.basename(base) + "_b.png") if (base + "_b.png") in R else ""
        W("- %s%s: %s" % (short(k), twin, anims(v)))
    W("")


actor_section("4. Enemies", "assets/sprites/enemies/", "actor",
              "Eleven enemy types; ten of them also come in a second palette (`_b`: turtle green, mini_rex blue, lizard red, dragon teal, insect cyan, bat blue, pterodactyl green, plant blue, egg_kid brown, rex grey) for Expert-only spawns or biome variety. No projectiles (the original has none). "
              "Enemies die by being knocked off-screen in an arc: use `dead` / `hit` as the tumbling pose. Feast mode swaps the sprite for a cell of `sprites/items/food.png`.")
actor_section("5. Bosses", "assets/sprites/bosses/", "boss",
              "Both bosses are integer 2x upscales so that they tower over the hero (Brute body 110 x 122 art px, Colossus 208 x 190).")
W("Brute hit zones (logical px relative to the feet point, facing right; mirror x when it faces left): body x -29..+26, y -61..0; head (weak point, bounce-safe) x -29..+18, y -61..-31; punching fist during `attack` frames 23-25: x +40..+70, y -34..-20.")
W("Colossus: place the pivot (bottom-right of the cell) on the arena floor at the right wall; the last 64 art px of the cell are the wall rim. Head rectangle per pose (art px inside the 260x224 cell): `idle` (48, 68)-(140, 130); `spit` / `rage` (88, 18)-(190, 110); `slam` (14, 88)-(110, 160); `hurt` (80, 18)-(190, 100). A single generous zone that works for every pose: x 14..190, y 18..130. Rock spawn point (open jaws in `spit`): cell (92, 70).")
W("")
actor_section("6. NPCs", "assets/sprites/npc/", "npc", "Tally companion and villagers for the ending stage / title screen.")

# ----------------------------------------------------------------------------- items
W("## 7. Collectibles (assets/sprites/items)")
W("")
for k in keys("assets/sprites/items/", "atlas"):
    v = R[k]
    W("### %s" % short(k))
    W("")
    W("%s, cell %s, grid %s, pivot %s. %s. Source: %s. Edit: %s." % (sz(v), fr(v), gr(v), pv(v), v.get("note", "").rstrip("."), v["source"], v["edits"]))
    W("")
    e = v["entries"]
    if "score" in e[0]:
        W("| index: name (points) |")
        W("|---|")
        line = []
        for it in e:
            line.append("%d: %s (%s)" % (it["index"], it["name"], format(it["score"], ",d").replace(",", " ")))
            if len(line) == 8:
                W("| " + " - ".join(line) + " |"); line = []
        if line:
            W("| " + " - ".join(line) + " |")
        W("")
    elif "meaning" in e[0]:
        table(["Index", "Name", "Meaning", "From"], [[it["index"], it["name"], it.get("meaning", ""), it.get("from", "")] for it in e])
    else:
        W("Cells: " + ", ".join("%d = %s" % (it["index"], it["name"]) for it in e) + ".")
        W("")
rows = []
for k in keys("assets/sprites/items/", "item"):
    v = R[k]
    rows.append([short(k), sz(v), fr(v), gr(v), pv(v), anims(v) or "-", v.get("note", "")])
table(["File", "Size", "Frame", "Grid", "Pivot", "Animations", "Note"], rows)
W("Not drawn on purpose: darkness triggers (invisible), flies (single pixels), score pop-ups (render with `fonts/font_hud.png`), code digits (font glyphs on `sprites/objects/code_stone.png`).")
W("")

# ----------------------------------------------------------------------------- objects
W("## 8. Interactive objects (assets/sprites/objects)")
W("")
rows = []
for k in keys("assets/sprites/objects/"):
    v = R[k]
    rows.append([short(k), sz(v), fr(v), gr(v), pv(v), anims(v) or "-", v.get("note", "")])
table(["File", "Size", "Frame", "Grid", "Pivot", "Animations", "Use"], rows)

# ----------------------------------------------------------------------------- fx
W("## 9. Effects (assets/sprites/fx)")
W("")
rows = []
for k in keys("assets/sprites/fx/"):
    v = R[k]
    rows.append([short(k), sz(v), fr(v), gr(v), pv(v), anims(v) or "static frames", v.get("note", "")])
table(["File", "Size", "Frame", "Grid", "Pivot", "Animations", "Use"], rows)

# ----------------------------------------------------------------------------- tiles
W("## 10. Tiles (assets/tiles)")
W("")
W("### 10.1 Terrain atlases")
W("")
W("Every terrain file is a 256 x 160 atlas of 8 x 5 tiles (32 x 32 art px) with the **same index meaning**, so one TileSet layout /")
W("one collision table serves all of them. Tiles 0-34 come from one terrain set of the pack; 35-37 are background-wall tiles; 38-39 spikes.")
W("")
table(["Index", "Name", "Meaning", "Collision"], [[i, "`%s`" % n, m, c] for i, (n, m, c) in enumerate(TERRAIN_TILES)])
W("Usage rules:")
W("")
W("- Outlines are part of the art: use `top*` where air is above, `left` / `right` where air is beside, `bottom*` where air is below, `fill` inside. No inner-corner tiles are needed: where ground meets a rising wall, put `fill` in the wall column at ground level and `left` / `right` above it.")
W("- Slopes: `slope45_*` rises 16 logical px over one tile; `gentle_*` rises 8 px per tile (low + high halves). Put the matching `under_*` tile directly below each slope tile. Slope tiles are solid from the top only along their surface line (store the left / right heights given above in the HEIGHT layer).")
W("- One-way platforms occupy the upper 16 art px (8 logical px) of their cell: collision line at the cell top, passable from below.")
W("- `spikes_floor` / `spikes_ceiling` are deadly; `hang_*`, `small_block`, `back_*` have no collision.")
W("- `fill_inset` is ordinary scenery with an inset panel: the suggested look for hidden bonus spots (swap to `back_fill` or `fill` when the spot is used up).")
W("")
rows = []
for k in keys("assets/tiles/", "terrain"):
    v = R[k]
    rows.append([short(k), sz(v), v["source"].split("tileset-1.png (", 1)[-1][:-1], v["edits"].split("appended")[-1].strip("; ") or "none beyond the re-cut", pal(k, 6)])
table(["File", "Size", "Terrain set", "Extra edits", "Main colours"], rows)
W("### 10.2 Liquids (animated tiles, 32 x 32)")
W("")
rows = []
for k in keys("assets/tiles/common/", "liquid"):
    v = R[k]
    rows.append([short(k), sz(v), gr(v), "0-5 surface loop @8 fps (top 4 art px are air); 6 body; 7 body with bubbles", v["note"], v["edits"]])
table(["File", "Size", "Grid", "Tiles", "Use", "Edit"], rows)
W("### 10.3 Per-biome palette notes")
W("")
table(["Biome", "Folder", "Terrain", "Palette / mood", "Parallax set"], [
    ["Jungle (world 1)", "`tiles/jungle`", "`terrain.png` (deep green), `terrain_grass.png` (light green meadow, tree houses)", "saturated greens `#34611b` / `#20b128` (deep) and `#64ae1d` / `#c6e402` (meadow) on a light-blue sky, warm brown wood; the brightest, friendliest biome", "`backgrounds/jungle` layer0-3"],
    ["Cave (world 2)", "`tiles/cave`", "`terrain.png` (violet rock with blue-lit tops), `terrain_stone.png` (tan stone for the boss arena / fortress parts)", "violet `#8e639f` + periwinkle `#8a8ebf` / `#8cbddf` against a near-black violet wall; cyan and violet crystals as accents", "`backgrounds/cave` layer0-2"],
    ["Ice (world 3)", "`tiles/ice`", "`terrain.png` (snow on ice), `terrain_rock.png` (frost-blue rock)", "white `#ffffff`, ice blue `#81c0d4` / `#b3dcfa`, navy `#2c3d5f`; recoloured props turn all greens into snow", "`backgrounds/ice` layer0-3"],
    ["Volcano (world 4)", "`tiles/volcano`", "`terrain.png` (orange volcanic rock), `terrain_obsidian.png` (dark keep / boss arena)", "hot oranges `#c95326` / `#e77f27` under a red dusk sky; obsidian `#504156` / `#7b6b80` interior with lava `#ce421a` / `#ffec82`", "`backgrounds/volcano` layer0-3 (outside), shaft_layer0-2 (inside)"],
    ["Feast Land (bonus)", "`tiles/feast`", "`terrain.png` (sponge-cake yellow), `terrain_icing.png` (strawberry icing), `terrain_biscuit.png`", "cake yellow `#eb9630` / `#ffd74f`, icing pink `#f8adba`, biscuit `#f3a950`, cream clouds and mint grass; food sprites provide the contrast", "`backgrounds/feast` layer0-3"],
    ["Village (ending / title)", "`tiles/village`", "use `tiles/jungle/terrain_grass.png`", "thatch orange and timber brown huts", "`backgrounds/jungle`"],
])
W("### 10.4 Props")
W("")
W("Single-image scenery, pivot = bottom-centre (ceiling pieces: top-centre, noted). No collision unless used as a gate / platform. All cut from the pack's `tileset-1.png`; ice and volcano versions are palette recolours, cave rocks are gradient-mapped to the violet rock, crystals are recoloured tusks.")
W("")
for biome in ("jungle", "cave", "ice", "volcano", "village"):
    ks = keys("assets/tiles/%s/props/" % biome)
    W("**%s** (`assets/tiles/%s/props/`, %d files): " % (biome, biome, len(ks)) + ", ".join("%s %s" % (os.path.basename(k)[:-4], sz(R[k])) for k in ks) + ".")
    W("")
W("Ceiling-anchored props (pivot top-centre): `stalactite`, `drips`, `drip_cap`, `icicle`, `vine_a`, `vine_b`, `moss_fringe`. `tree_canopy_*` sits on `tree_trunk` (overlap 8 px). `foliage_block` / `foliage_clump` are meant as foreground (drawn in front of actors).")
W("")

# ----------------------------------------------------------------------------- backgrounds
W("## 11. Parallax backgrounds (assets/backgrounds)")
W("")
W("Every layer is 360 px high and already positioned vertically: draw all layers of a set at y = 0, back to front, and repeat them")
W("horizontally (`texture_repeat`). Width = loop length. `scroll` = suggested horizontal parallax factor (camera x multiplier).")
W("")
rows = []
for k in keys("assets/backgrounds/"):
    v = R[k]
    rows.append([short(k), sz(v), v["scroll"], "opaque" if "layer0" in k else "transparent sky area", v["edits"]])
table(["File", "Size", "Scroll", "Alpha", "Edits"], rows)

# ----------------------------------------------------------------------------- ui / fonts
W("## 12. UI, fonts, icon, splash")
W("")
rows = []
for k in keys("assets/ui/") + ["assets/icon.png", "assets/splash.png"]:
    v = R[k]
    ent = v.get("entries")
    extra = (". Cells: " + ", ".join("%d %s" % (e["index"], e["name"]) for e in ent) + ".") if ent else ""
    rows.append([short(k), sz(v), fr(v), gr(v), v.get("note", "") + extra])
table(["File", "Size", "Cell", "Grid", "Use"], rows)
rows = []
for k in keys("assets/fonts/"):
    v = R[k]
    if v["kind"] == "font":
        rows.append([short(k), sz(v), fr(v) + " cells, " + gr(v), v["charset"], v["note"]])
    else:
        rows.append([short(k), "TTF", "-", "Latin, Latin Extended-A, Cyrillic" if "press_start" in k else "Latin, Latin Extended-A, most of Cyrillic", v["note"]])
table(["File", "Size", "Grid", "Characters", "Use"], rows)
W("HUD layout used in the mocks (art px, 640x360): lives icon at (8, 6) + `x2` at (58, 16); score at (112, 16); three hearts at x 270 / 304 / 338, y 8;")
W("bonus letters at x 430 + 40 n, y 4-10 (staggered); boss pips from (10, 334) every 18 px. Keep a 16 px safe margin on phones.")
W("")

# ----------------------------------------------------------------------------- audio
W("## 13. Audio (assets/audio)")
W("")
W("All 79 files are byte-identical copies of the files recorded in the staging area (WAV 16-bit or OGG Vorbis); nothing was edited or re-encoded by the art pipeline.")
W("Six music tracks exist only as WAV at the source and were transcoded to OGG Vorbis (quality 0.6, sample-exact length) by the audio scout; they are marked in the table.")
W("Apply `volume_db` in the AudioStreamPlayer (masters differ by up to 20 dB between authors).")
W("Looping files: set the import flag `loop = true` (OGG) / loop mode Forward (WAV).")
W("")
W("### 13.1 Sound effects")
W("")
rows = []
for k in keys("assets/audio/sfx/"):
    v = R[k]
    rows.append([short(k), v["event"], "%.2f" % v["duration"], "yes" if v["loop"] else "no", "%+.1f" % (v["volume_db"] + 0.0 if abs(v["volume_db"]) > 0.04 else 0.0), v["author"]])
table(["File", "Game event", "Seconds", "Loop", "volume_db", "Author (all CC0)"], rows)
W("### 13.2 Music")
W("")
rows = []
for k in keys("assets/audio/music/"):
    v = R[k]
    rows.append([short(k), v["event"] + (" [OGG transcode of the author's WAV]" if "ogg_converted" in v["source"] else ""), "%.1f" % v["duration"], "yes" if v["loop"] else "no", "%+.1f" % v["volume_db"], v["author"]])
table(["File", "Context", "Seconds", "Loop", "volume_db", "Author (all CC0)"], rows)
W("### 13.3 Original cue slots -> files (GAMEPLAY 10.1)")
W("")
table(["Slot", "Original use", "File"], [
    ["0", "hammer swing; kill-all / grenade explosion", "`club_swing_b.wav`; `explosion_a.wav`"],
    ["1", "heavy hurt: skull, boss hit, boss projectile; lights off", "`player_hurt_b.wav`"],
    ["2", "enemy killed by a weapon; Colossus roar when hit", "`enemy_death_a.wav` / `_b`; `boss_roar_a.wav`"],
    ["3", "bounce on an enemy or boss head", "`spring_bounce_a.wav`"],
    ["4", "big pick-up: giant bonus, heart, 1UP", "`gem_pickup_a.wav`, `energy_refill_a.wav`, `one_up_a.wav`"],
    ["5", "club swing", "`club_swing_a.wav`"],
    ["7", "hero death", "`player_death_a.wav` + music `player_death_a.ogg`"],
    ["8", "normal pick-up; boss hit by a weapon; tally item", "`food_pickup_a..d.wav`; `boss_hit_a.wav`; `tally_tick_a.wav`"],
    ["9", "hero hurt by an enemy", "`player_hurt_a.wav`"],
    ["10", "axe throw", "`projectile_throw_b.wav`"],
])

# ----------------------------------------------------------------------------- edits
W("## 14. Generated or modified assets (edit log)")
W("")
W("Everything below was produced by the scripts in `docs/art/pipeline/` (Python + Pillow, nearest-neighbour only, palette-preserving recolours applied per unique colour). Files not listed are byte-identical or lossless re-packs of the source art.")
W("")
table(["What", "Files", "How"], [
    ["Hero with weapons", "`sprites/player/hero*.png`", "the pack's club / hammer / axe / boomerang item sprite rotated about its grip (upscale-rotate-point-sample, outline rebuilt) and composited behind the body in every carry and attack frame; slash arc from `fx/effects/1.png`"],
    ["New hero poses", "same", "`attack_up`, `attack_crouch`, `attack_air`, `victory`, `crawl`, `glide` assembled from existing frames"],
    ["Hang poses", "`sprites/enemies/bat*.png`, `insect*.png`", "one frame flipped vertically and re-anchored"],
    ["Mirrored sheets", "`turtle*.png`, `rex*.png`", "source faces left; mirrored so that every actor faces right"],
    ["Bosses", "`sprites/bosses/*.png`", "integer 2x; `taunt` / `pound` loops built from existing frames; Colossus = T-rex gradient-mapped to stone / lava-glow / dead ramps, cropped at the wall line, obsidian rim added"],
    ["Terrain atlases", "`tiles/*/terrain*.png`", "re-cut to the common 40-tile layout; right-hand pieces mirrored; `ice/terrain_rock`, `volcano/terrain_obsidian`, `feast/terrain_icing` are gradient-mapped recolours"],
    ["Liquids", "`tiles/common/lava.png`, `ice_water.png`", "exact colour swap of the water tiles"],
    ["Biome props", "`tiles/ice/props`, `tiles/volcano/props`, cave rocks, crystals, icicle", "palette recolours of the jungle / neutral props"],
    ["Objects", "`exit_totem.png`, `checkpoint.png`, `glider.png`, `breakable_block_*.png`, `platform_ice.png`, `platform_stone.png`", "composites / recolours described in section 8"],
    ["FX", "`splash_water.png`, `splash_lava.png`, `falling_ember.png`, `projectile_*.png`", "recolours and lossless 90 degree rotations"],
    ["Backgrounds", "`backgrounds/**`", "cropped to 360 px, pre-positioned, mirrored copy appended for seamless looping; ice / volcano / feast / cave sets are gradient-mapped recolours of the pack's jungle and rock layers"],
    ["Icons at 2x", "`sprites/items/food.png` (0-39), `treasure.png`, parts of `pickups.png`, `ui/hud_heart.png`, `ui/icons.png`", "16 px icons scaled 2x"],
    ["Giant food", "`sprites/items/giant_bonus.png`", "32 px sprites scaled 2x + 2 px `#272018` outline"],
    ["Touch buttons", "`ui/touch_buttons.png`, `ui/touch_pause.png`", "2x, gradient-mapped to sandstone, pressed row generated"],
    ["UI composites", "`ui/panel.png`, `ui/bar_fill.png`, `ui/title_logo.png`, `ui/world_map_background.png`, `icon.png`, `splash.png`, `fonts/font_title.png`", "re-cut / composed from pack pieces"],
])

# ----------------------------------------------------------------------------- sources
W("## 15. Sources and licences")
W("")
W("%d source packs, %d tier A (CC0), %d tier B (SIL OFL fonts), 0 tier C. Details and licence texts: `CREDITS.md`, `assets/licenses/`." % (
    len(CREDITS), sum(1 for c in CREDITS if c["tier"] == "A"), sum(1 for c in CREDITS if c["tier"] == "B")))
W("")
table(["Pack", "Author", "Licence", "Used for"], [[c["title"], c["author"], c["license"], c["use"]] for c in CREDITS])

W("## 16. Known gaps")
W("")
for g in [
    "No sound was auditioned by ear (the pipeline has no audio output): picks rest on the audio scout's measurements; a human listen-through of `assets/audio` is still required, and `volume_db` values are starting points.",
    "The Rooted Guardian (optional tree-stump mid-boss, GAMEPLAY 6.2) has no dedicated sprite.",
    "Bosses are pixel-doubled (4 px outlines next to the 2 px outlines of everything else); no boss-sized art exists in the anchor style.",
    "The hero has no dedicated skid, out-of-breath or idle-fidget animation: use `land` for the skid and `idle` at double speed for panting.",
    "Terrain has no drawn inner-corner tiles and one top variant per set; long flat stretches repeat every 32 px (break them up with props and `fill_b`).",
    "Hang-glider: one static overlay sprite (no inflate / fold animation).",
    "Feast Land has no prop folder of its own: decorate it with `sprites/items/giant_bonus.png` cells and food sprites.",
    "World-map level markers and the Beginner-wall castle picture are not drawn; compose them from `ui/world_map_background.png`, `ui/icons.png` and village props.",
    "`font_hud.png` covers ASCII and a few Western accents only; use `press_start_2p.ttf` / `pixelify_sans.ttf` for other languages.",
]:
    W("- " + g)
W("")

# Section 17 (2.0 "The Far Shore") is generated by docs/art/expansion/pipeline/build_expansion.py; keep it when this
# script rewrites the file.
sys.path.insert(0, os.path.join(ROOT, "docs", "art", "expansion", "pipeline"))
import manifest_expansion  # noqa: E402
if os.path.exists(manifest_expansion.REG_PATH):
    out.extend(manifest_expansion.section_lines())
    out.append("")
# Section 18 (the file ledger: source, author, licence and changes of every file) is written by
# tools/audit_assets.py --write-ledger; keep the block as it stands, then run that tool: the audit fails on a ledger
# that is not what the registries give.
LEDGER_BEGIN = "<!-- audit-ledger: generated by tools/audit_assets.py --write-ledger - begin -->"
LEDGER_END = "<!-- audit-ledger: end -->"
MANIFEST_PATH = os.path.join(ROOT, "docs", "ASSET_MANIFEST.md")
if os.path.exists(MANIFEST_PATH):
    old_manifest = open(MANIFEST_PATH, encoding="utf-8").read()
    if LEDGER_BEGIN in old_manifest and LEDGER_END in old_manifest:
        out.append(old_manifest[old_manifest.index(LEDGER_BEGIN):old_manifest.index(LEDGER_END) + len(LEDGER_END)])
        out.append("")
open(MANIFEST_PATH, "w", encoding="utf-8", newline="\n").write("\n".join(out))
print("manifest lines:", len(out))

# ============================================================================= CREDITS.md, assets/licenses/README.md
# Both are maintained by hand since the release legal audit (author / URL corrections, the changes column, the engine
# and FreeType notices, the licence-text index; see docs/THIRD_PARTY.md), so they are only checked here: every pack the
# assets come from must be credited in both, by its source URL and its licence file.
credits_md = open(os.path.join(ROOT, "CREDITS.md"), encoding="utf-8").read()
licences_md = open(os.path.join(ASSETS, "licenses", "README.md"), encoding="utf-8").read()
missing = []
for r in CREDITS:
    url = r["url"].split(" and ")[0]
    if url not in credits_md:
        missing.append("CREDITS.md lacks %s (%s)" % (r["title"], url))
    if os.path.basename(r["file"]) not in licences_md:
        missing.append("assets/licenses/README.md lacks %s" % os.path.basename(r["file"]))
for name in ["godot_engine.txt", "godot_third_party.txt"]:
    if not os.path.exists(os.path.join(ASSETS, "licenses", name)):
        missing.append("assets/licenses/%s is missing (regenerate it from the engine, see assets/licenses/README.md)" % name)
if missing:
    print("\n".join("CREDITS CHECK: " + m for m in missing))
    sys.exit(1)
print("credits + licence readme checked: %d packs credited" % len(CREDITS))
