"""The 2.0 section of docs/ASSET_MANIFEST.md, generated from registry_expansion.json (art-A files and the art-B
hand-over rows merged by build_expansion.py). The 1.0 sections 1-16 stay as docs/art/pipeline/build_manifest.py writes
them; that script appends this section too (section_lines()), so a full 1.0 rebuild keeps it.

The section sits between the markers BEGIN / END below; build_expansion.py replaces only that block in place.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REG_PATH = os.path.join(HERE, "registry_expansion.json")
BEGIN = "<!-- expansion-2.0: generated by docs/art/expansion/pipeline/build_expansion.py - begin -->"
END = "<!-- expansion-2.0: end -->"


def _load():
    with open(REG_PATH, encoding="utf-8") as f:
        return json.load(f)


def _sz(v):
    return "%dx%d" % tuple(v["size"]) if "size" in v else "-"


def _fr(v):
    return "%dx%d" % tuple(v["frame"]) if "frame" in v else "-"


def _gr(v):
    return "%dx%d" % tuple(v["grid"]) if "grid" in v else "-"


def _pv(v):
    return "(%d, %d)" % tuple(v["pivot"]) if "pivot" in v else "-"


def _rng(fr):
    fr = list(fr)
    if len(fr) == 1:
        return str(fr[0])
    if fr == list(range(fr[0], fr[-1] + 1)):
        return "%d-%d" % (fr[0], fr[-1])
    return ",".join(str(f) for f in fr)


def _anims(v):
    items = sorted(v.get("anims", {}).items(), key=lambda kv: (kv[1]["frames"][0], kv[0]))
    if not items:
        return "-"
    return "; ".join("**%s** %s @%s fps %s" % (n, _rng(a["frames"]), a["fps"], "loop" if a["loop"] else "once")
                     for n, a in items)


def _short(k):
    return "`" + k[len("assets/"):] + "`"


def section_lines(reg=None):
    full = _load() if reg is None else reg
    R = {k: v for k, v in full.items() if k.startswith("assets/")}
    extra = full.get("_meta", {})
    out = []
    W = out.append

    def table(head, rows):
        W("| " + " | ".join(head) + " |")
        W("|" + "|".join("---" for _ in head) + "|")
        for r in rows:
            W("| " + " | ".join(str(c).replace("|", "/").replace("\n", " ") for c in r) + " |")
        W("")

    def keys(section=None, owner="art-A"):
        return sorted(k for k, v in R.items() if v.get("owner", "art-A") == owner
                      and (section is None or v.get("section") == section))

    W(BEGIN)
    W("")
    W("## 17. Expansion 2.0 \"The Far Shore\"")
    W("")
    W("Every file added for 2.0 (DESIGN.md F.1). Generated by `docs/art/expansion/pipeline/build_expansion.py` from "
      "`docs/art/expansion/pipeline/registry_expansion.json`: art-A's files (hero colours, co-op and Book II objects, "
      "items, effects, UI, liquids, versus art) are built by that pipeline; art-B's world files and the audio owner's "
      "sounds and music arrive with their rows through `.tools/asset_candidates/expansion/_handover/` and are merged "
      "here (owner column; the audio rows are checked against the files by sha256). The conventions of section 1 "
      "hold unchanged: anchor style, 2 px `#272018` outline, nearest-neighbour, integer scales only, every sheet "
      "<= 2048 px. Sections 17.10-17.12 follow the edit log so that the numbers 17.1-17.9 stay what the code cites. "
      "Proof sheets: `docs/art/expansion/*.png` (hero colours `heroes_*.png`, `hero_patterns*.png`, "
      "`hero_palette_swatches.png`; objects `coop_objects_frames.png`, `coop_scene_canyon.png`, `coop_scene_cave.png`, "
      "`book2_objects.png`, `book2_scene_fen.png`, `book2_scene_gulch.png`; liquids `liquids_tar_floor.png`; versus "
      "`versus_totem_ring.png`; readability `mp_indicators.png`, `eggs_p1_p4.png`; phase 2: the map page "
      "`far_shore_map.png`, the paintings `paintings_slab_mural.png`, versus screens and HUD `versus_screens.png`, "
      "Feast Lands `feast_d_e.png`, world objects `world_objects_p2.png`).")
    W("")

    # ------------------------------------------------------------------ 17.1 hero colours
    W("### 17.1 Hero colours P1-P4: palette LUTs and loincloth patterns")
    W("")
    W("Player colours are a palette swap in a shader (TECH_AUDIT 5.3: one shared `ShaderMaterial` per slot, no baked "
      "sheets; +0 MB). P1 with `yellow` + pattern `spots` reproduces 1.0 exactly: the build asserts it pixel for pixel "
      "on all five hero sheets. The shader contract is in `hero_palettes.json` (`shader`) and in the docstring of "
      "`build_hero_palettes.py`, whose `Palettes.apply()` is the executable reference.")
    W("")
    pal_keys = sorted(k for k in R if "/palettes/" in k)
    table(["File", "Size", "Use"], [[_short(k), _sz(R[k]), R[k].get("note", "")] for k in pal_keys])
    meta_path = os.path.join(HERE, "..", "..", "..", "..", "assets", "sprites", "player", "palettes",
                             "hero_palettes.json")
    meta = None
    if os.path.exists(meta_path):
        with open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)
    if meta:
        roles = meta["lut_roles"]
        W("LUT entries (x of the 16 x 1 texture; 10-15 unused): " +
          ", ".join("%d `%s`" % (i, r) for i, r in enumerate(roles)) + ".")
        W("")
        table(["Colour"] + roles, [[n] + ["`%s`" % p[r] for r in roles] for n, p in meta["palettes"].items()])
        W("Slot defaults: " + ", ".join("%s %s / %s" % (s.upper(), d["colour"], d["pattern"])
                                        for s, d in meta["slot_defaults"].items()) +
          ". Arena swaps (E.9): " + ", ".join("%s: %s" % (b, ", ".join("%s -> %s" % kv for kv in m.items()))
                                              for b, m in meta["arena_swaps"].items()) +
          ". `gold` is the 25-paintings unlock (C.9); `white` is P4 on green arenas.")
        W("")
        table(["#", "Pattern", "Rule", "Unlock"],
              [[p["index"], p["name"], p["rule"], p["unlock"]] for p in meta["patterns"]])
    chk = R.get("assets/sprites/player/palettes/hero_palettes.json", {}).get("checks")
    if chk:
        W("Readability checks (recomputed by every build; CIEDE2000, simulations %s): smallest difference between "
          "two slot defaults over all simulations: loincloth %.1f, loincloth shadow %.1f (a value above about 20 reads "
          "as a clearly different colour). The two light cloths (yellow, blue) and the two dark ones (pink, green) "
          "differ in hue along the blue-yellow axis that red-green dichromats keep, and every pair also differs in "
          "pattern; tags, arrows and eggs use the same split (`mp_indicators.png`)."
          % (", ".join(chk["sims"]), chk["cvd_min_de2000"]["cloth"], chk["cvd_min_de2000"]["cloth_shadow"]))
        W("")
        worst = []
        for b, d in chk["biome_camouflage"].items():
            for n, v in d.items():
                if v >= 0.1:
                    worst.append("%s on %s %.0f %%" % (n, b, 100 * v))
        W("Background camouflage (share of the background pixels behind a standing hero within CIEDE2000 10 of the "
          "loincloth colour): everything under 10 %% except %s. The dark per-slot outline keeps those heroes "
          "readable (`heroes_biomes.png`); green is swapped for white on jungle / swamp arenas."
          % ("; ".join(worst) if worst else "nothing"))
        W("")

    # ------------------------------------------------------------------ 17.2 - 17.5 file tables
    def file_table(title, sections, intro=None):
        ks = [k for sec in sections.split("+") for k in keys(sec)]
        if not ks:
            return
        W(title)
        W("")
        if intro:
            W(intro)
            W("")
        table(["File", "Size", "Frame", "Grid", "Pivot", "Animations", "Use"],
              [[_short(k), _sz(R[k]), _fr(R[k]), _gr(R[k]), _pv(R[k]), _anims(R[k]), R[k].get("note", "")]
               for k in ks])

    file_table("### 17.2 Player sheets", "player",
               "`hero_spear.png` has the layout, animations, pivots and cloth pixels of `hero.png` (section 3); the "
               "spear is a thrown weapon like the axe (release frames bare-handed).")
    file_table("### 17.3 Objects: co-op (DESIGN D.5) and Book II (C.2-C.8)", "objects",
               "Sheets with a `rows` list hold one skin per row: the biome rows follow `LevelData.BIOMES` (jungle, "
               "cave, ice, volcano, feast, village, canyon, swamp, coast, ruins, sky), so the row of a level's biome "
               "is `LevelData.BIOMES.find(biome)`.")
    file_table("### 17.4 Items and effects", "items+fx")
    file_table("### 17.5 UI", "ui")

    # ------------------------------------------------------------------ 17.6 art-B hand-over
    kb = keys(None, "art-B")
    W("### 17.6 Worlds and creatures (art-B hand-over)")
    W("")
    if kb:
        W("Rows handed over by art-B (`.tools/asset_candidates/expansion/_handover/`), checked against the files: "
          "size measured from the PNG, at most 2048 px a side, every source pack credited, CC0. Actor pivots follow "
          "section 1 (`cell_h - 16`); body boxes are art-B's measurements of the first idle frame (suggestions).")
        W("")

        def use(v):
            t = v.get("note") or ""
            if "scroll" in v:
                t += " (scroll %.2f)" % v["scroll"]
            if v.get("tiles") == "TERRAIN_TILES":
                t += "; layout and collision of section 10.1 (40 tiles)"
            if "tiles_inline" in v:
                t += "; tiles: " + "; ".join("%s %s" % kv for kv in v["tiles_inline"].items())
            if "zones_logical" in v:
                t += "; zones (logical px from the feet, facing right): " + "; ".join(
                    "%s %s" % (z, b) for z, b in v["zones_logical"].items())
            return t
        table(["File", "Size", "Frame", "Grid", "Pivot", "Facing", "Body box (logical)", "Animations", "Use"],
              [[_short(k), _sz(R[k]), _fr(R[k]), _gr(R[k]), _pv(R[k]), R[k].get("facing", "-"),
                "%dx%d" % tuple(R[k]["body_box_logical"]) if "body_box_logical" in R[k] else "-", _anims(R[k]),
                use(R[k])] for k in kb])
        notes = extra.get("handover_notes", [])
        if notes:
            W("Notes from the hand-over (art-B's words, kept here because the staging folder is not versioned):")
            W("")
            out.extend(notes)
            W("")
    else:
        W("(none yet)")
        W("")

    # ------------------------------------------------------------------ 17.7 edit log
    W("### 17.7 Edit log (2.0)")
    W("")
    table(["File", "Owner", "Source", "Edits"],
          [[_short(k), R[k].get("owner", "art-A"), R[k].get("source", "-"), R[k].get("edits", "-")]
           for k in sorted(R)])

    # ------------------------------------------------------------------ 17.8 sources
    W("### 17.8 Sources and licences (2.0)")
    W("")
    packs = extra.get("packs", {})
    W("All CC0 1.0 (tier A); no CC-BY, share-alike or non-commercial file (DESIGN F.3). Shipped 1.0 files that are "
      "recoloured or composited keep their original source (section 15). Licence texts: `assets/licenses/`; "
      "credits: `CREDITS.md`.")
    W("")
    table(["Pack", "Author", "Licence", "Licence file", "2.0 files"],
          [[p["title"], p["author"], p["license"], "`%s`" % p["file"], p["count"]] for p in packs.values()])
    apacks = extra.get("audio_packs", {})
    if apacks:
        W("Audio (17.12): every pack CC0 1.0; packs new in 2.0 have their licence file written from the evidence "
          "recorded at download (`LICENSE_INFO.md` of the staging folder), the 1.0 packs keep their 1.0 files.")
        W("")
        table(["Pack", "Author", "Licence", "Licence file", "2.0 files", "New in 2.0"],
              [[p["title"], p["author"], p["license"], "`%s`" % p["file"], p["count"], "yes" if p["new"] else "-"]
               for p in apacks.values()])

    # ------------------------------------------------------------------ 17.9 gaps
    W("### 17.9 Known gaps (2.0, art-A)")
    W("")
    for g in extra.get("gaps", []):
        W("- " + g)
    W("")

    # ------------------------------------------------------------------ 17.10 liquids
    kt = keys("tiles")
    if kt:
        W("### 17.10 Book II liquids and the tar floor (DESIGN C.4, PHYSICS C.5)")
        W("")
        W("`liquid = tar | honey | syrup` strips in the exact format of section 10.2, and the look of the ':' tar "
          "floor for every liquid in the 4 x 1 layout of art-B's `tiles/canyon/mud_floor.png` (world-A appends it "
          "to the liquid strip). Drawn surface line at art row 6 of a ':' cell, collision surface at art row 12 "
          "(`PROFILE_TAR`, 6 logical px).")
        W("")

        def tiles(v):
            t = v.get("note", "")
            if "tiles_inline" in v and v.get("kind") != "liquid":       # the liquid notes already name the tiles
                t += "; tiles: " + "; ".join("%s %s" % kv for kv in v["tiles_inline"].items())
            if "palette" in v:
                t += "; ramp " + " ".join("`%s`" % c for c in v["palette"])
            return t
        table(["File", "Size", "Frame", "Grid", "Animations", "Use"],
              [[_short(k), _sz(R[k]), _fr(R[k]), _gr(R[k]), _anims(R[k]), tiles(R[k])] for k in kt])

    # ------------------------------------------------------------------ 17.11 versus
    kv = keys("versus")
    if kv:
        W("### 17.11 Versus art (DESIGN E.3 / E.8 / E.9)")
        W("")
        W("The cookpot, the spawn pads, the crown and the stack pictures of the G1 slice (Totem Ring, Grub Stack), "
          "and phase 2's who-is-who and screen art: portraits and corner-panel heads in every hero colour and three "
          "expressions, the round sundial, the medal discs of the awards and tally medals, the scoreboard plate, the "
          "results cave wall with the heroes painted on it. The Golden Drumstick item is in 17.4, the hit sparks in "
          "the attacker's colour (`sprites/fx/hit_stars_players.png`) in 17.4 too. Colour rows follow "
          "`UiPlayers.PALETTE_COLOURS` (yellow, blue, pink, green, white, gold); the tags and arrows of 17.5 have a "
          "row per colour as well.")
        W("")
        table(["File", "Size", "Frame", "Grid", "Pivot", "Animations", "Use"],
              [[_short(k), _sz(R[k]), _fr(R[k]), _gr(R[k]), _pv(R[k]), _anims(R[k]), R[k].get("note", "")]
               for k in kv])

    # ------------------------------------------------------------------ 17.12 audio
    ka = keys(None, "audio")
    if ka:
        W("### 17.12 Audio (audio owner's hand-over, DESIGN F.2)")
        W("")
        W("Rows handed over by the audio owner (`.tools/asset_candidates/expansion/_handover/audio/*.json`), checked "
          "here: the file exists and its sha256 equals the hand-over's. Loudness follows the 1.0 rules (13.4: music "
          "-18 LUFS, effects -14 LUFS short-term, true peak <= -1 dBTP); `volume_db` is the AudioTable value that "
          "plays the file at its target (core-A owns `AudioTable` and the `.import` files). Sources and edits per "
          "file: 17.7.")
        W("")

        def lufs(v):
            if v.get("lufs_integrated") is not None:
                return "%.1f" % v["lufs_integrated"]
            if v.get("lufs_short") is not None:
                return "%.1f (short)" % v["lufs_short"]
            return "-"

        def num(v, k, f="%.1f"):
            return f % v[k] if v.get(k) is not None else "-"

        def loop(v):
            if not v.get("loop"):
                return "-"
            r = v.get("loop_region_frames")
            return "loop" + (" %d-%d" % tuple(r) if r else "")
        table(["File", "Kind", "Cues", "Seconds", "Loop", "LUFS", "True peak dBTP", "volume_db", "Played at", "Role"],
              [[_short(k), R[k].get("kind", "-"), ", ".join("`%s`" % n for n in R[k].get("names", [])),
                num(R[k], "seconds", "%.2f"), loop(R[k]), lufs(R[k]), num(R[k], "true_peak_dbtp"),
                num(R[k], "volume_db"), R[k].get("played_at") or "-", R[k].get("role", "")] for k in ka])
    # ------------------------------------------------------------------ 17.13 the Far Shore map page, paintings
    kf = keys("far_shore")
    if kf:
        W("### 17.13 The Far Shore map page and the Cave Paintings (DESIGN A.1, C.9)")
        W("")
        W("Book II's map page and the pictures of the 30 Cave Paintings for ui-A's map, slab and unlocks screen. "
          "The painting slab is screen UI in the lower-right corner of the map screen (world_map.gd), not part of "
          "the map picture.")
        W("")
        table(["File", "Size", "Frame", "Grid", "Use"],
              [[_short(k), _sz(R[k]), _fr(R[k]), _gr(R[k]), R[k].get("note", "")] for k in kf])
        mp = R.get("assets/ui/world_map_far_shore.png", {})
        if mp.get("markers"):
            W("Map stops on `ui/world_map_far_shore.png` (map px, the marker's centre; the hero stands on it, the "
              "number plate 12-24 px below):")
            W("")
            table(["Stop"] + list(mp["markers"].keys()),
                  [["(x, y)"] + ["(%d, %d)" % tuple(v) for v in mp["markers"].values()]])
        pt = R.get("assets/ui/paintings.png", {})
        if pt.get("themes"):
            W("Painting pictures (`ui/paintings.png`, cell = index) and the level whose story each suits:")
            W("")
            table(["Index", "Figure", "Suits"], [[t["index"], t["figure"], t["suggested_for"]] for t in pt["themes"]])

    # ------------------------------------------------------------------ 17.14 feast
    kfe = keys("feast")
    if kfe:
        W("### 17.14 Feast Land D / E skins (DESIGN A.3)")
        W("")
        W("Honey Falls (`bonus_d`) and Pudding Lagoon (`bonus_e`): two terrain atlases in the 40-tile layout and "
          "collision of 10.1, and `props/feast/<name>` pictures (`assets/tiles/feast/props/`, no collision). Their "
          "liquids (`honey`, `syrup`), ':' floors, the soda geyser and the wafer raft are phase-1 files (17.3, 17.10).")
        W("")
        table(["File", "Size", "Pivot", "Use"],
              [[_short(k), _sz(R[k]), _pv(R[k]), R[k].get("note", "")] for k in kfe])

    # ------------------------------------------------------------------ 17.15 new uses of 1.0 files
    uses = extra.get("reuse_1_0", [])
    if uses:
        W("### 17.15 2.0 uses of shipped 1.0 files")
        W("")
        W("Shipped 1.0 files (sections 3-12, unchanged) that 2.0 code draws for a new purpose:")
        W("")
        table(["File", "2.0 use"], [["`%s`" % f, u] for f, u in uses])

    W(END)
    return out


def replace_in(path, lines):
    """put the section into the manifest: replace the marked block, or append it"""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    block = "\n".join(lines)
    if BEGIN in text and END in text:
        a = text.index(BEGIN)
        b = text.index(END) + len(END)
        text = text[:a] + block + text[b:]
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
