"""The 2.0 section of docs/ASSET_MANIFEST.md, generated from registry_expansion.json (art-A files and the art-B
hand-over rows merged by build_expansion.py). The 1.0 sections 1-16 stay as docs/art/pipeline/build_manifest.py writes
them; that script appends this section too (section_lines()), so a full 1.0 rebuild keeps it.

The section sits between the markers BEGIN / END below; build_expansion.py replaces only that block in place.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REG_PATH = os.path.join(HERE, "registry_expansion.json")
BEGIN = "<!-- expansion-2.0: generated by docs/art/expansion/pipeline/build_expansion.py - begin -->"
END = "<!-- expansion-2.0: end -->"


def _load():
    with open(REG_PATH, encoding="utf-8") as f:
        return json.load(f)


def _sz(v):
    return "%dx%d" % tuple(v["size"]) if "size" in v else "-"


def _fr(v):
    return "%dx%d" % tuple(v["frame"]) if "frame" in v else "-"


def _gr(v):
    return "%dx%d" % tuple(v["grid"]) if "grid" in v else "-"


def _pv(v):
    return "(%d, %d)" % tuple(v["pivot"]) if "pivot" in v else "-"


def _rng(fr):
    fr = list(fr)
    if len(fr) == 1:
        return str(fr[0])
    if fr == list(range(fr[0], fr[-1] + 1)):
        return "%d-%d" % (fr[0], fr[-1])
    return ",".join(str(f) for f in fr)


def _anims(v):
    items = sorted(v.get("anims", {}).items(), key=lambda kv: (kv[1]["frames"][0], kv[0]))
    if not items:
        return "-"
    return "; ".join("**%s** %s @%s fps %s" % (n, _rng(a["frames"]), a["fps"], "loop" if a["loop"] else "once")
                     for n, a in items)


def _short(k):
    return "`" + k[len("assets/"):] + "`"


def section_lines(reg=None):
    full = _load() if reg is None else reg
    R = {k: v for k, v in full.items() if k.startswith("assets/")}
    extra = full.get("_meta", {})
    out = []
    W = out.append

    def table(head, rows):
        W("| " + " | ".join(head) + " |")
        W("|" + "|".join("---" for _ in head) + "|")
        for r in rows:
            W("| " + " | ".join(str(c).replace("|", "/").replace("\n", " ") for c in r) + " |")
        W("")

    def keys(section=None, owner="art-A"):
        return sorted(k for k, v in R.items() if v.get("owner", "art-A") == owner
                      and (section is None or v.get("section") == section))

    W(BEGIN)
    W("")
    W("## 17. Expansion 2.0 \"The Far Shore\"")
    W("")
    W("Every file added for 2.0 (DESIGN.md F.1). Generated by `docs/art/expansion/pipeline/build_expansion.py` from "
      "`docs/art/expansion/pipeline/registry_expansion.json`: art-A's files (hero colours, co-op objects, items, "
      "effects, UI) are built by that pipeline; art-B's world files arrive with their rows through "
      "`.tools/asset_candidates/expansion/_handover/` and are merged here (owner column). The conventions of section 1 "
      "hold unchanged: anchor style, 2 px `#272018` outline, nearest-neighbour, integer scales only, every sheet "
      "<= 2048 px. Proof sheets: `docs/art/expansion/*.png` (hero colours `heroes_*.png`, `hero_patterns*.png`, "
      "`hero_palette_swatches.png`; objects `coop_objects_frames.png`, `coop_scene_canyon.png`, `coop_scene_cave.png`; "
      "readability `mp_indicators.png`, `eggs_p1_p4.png`).")
    W("")

    # ------------------------------------------------------------------ 17.1 hero colours
    W("### 17.1 Hero colours P1-P4: palette LUTs and loincloth patterns")
    W("")
    W("Player colours are a palette swap in a shader (TECH_AUDIT 5.3: one shared `ShaderMaterial` per slot, no baked "
      "sheets; +0 MB). P1 with `yellow` + pattern `spots` reproduces 1.0 exactly: the build asserts it pixel for pixel "
      "on all five hero sheets. The shader contract is in `hero_palettes.json` (`shader`) and in the docstring of "
      "`build_hero_palettes.py`, whose `Palettes.apply()` is the executable reference.")
    W("")
    pal_keys = sorted(k for k in R if "/palettes/" in k)
    table(["File", "Size", "Use"], [[_short(k), _sz(R[k]), R[k].get("note", "")] for k in pal_keys])
    meta_path = os.path.join(HERE, "..", "..", "..", "..", "assets", "sprites", "player", "palettes",
                             "hero_palettes.json")
    meta = None
    if os.path.exists(meta_path):
        with open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)
    if meta:
        roles = meta["lut_roles"]
        W("LUT entries (x of the 16 x 1 texture; 10-15 unused): " +
          ", ".join("%d `%s`" % (i, r) for i, r in enumerate(roles)) + ".")
        W("")
        table(["Colour"] + roles, [[n] + ["`%s`" % p[r] for r in roles] for n, p in meta["palettes"].items()])
        W("Slot defaults: " + ", ".join("%s %s / %s" % (s.upper(), d["colour"], d["pattern"])
                                        for s, d in meta["slot_defaults"].items()) +
          ". Arena swaps (E.9): " + ", ".join("%s: %s" % (b, ", ".join("%s -> %s" % kv for kv in m.items()))
                                              for b, m in meta["arena_swaps"].items()) +
          ". `gold` is the 25-paintings unlock (C.9); `white` is P4 on green arenas.")
        W("")
        table(["#", "Pattern", "Rule", "Unlock"],
              [[p["index"], p["name"], p["rule"], p["unlock"]] for p in meta["patterns"]])
    chk = R.get("assets/sprites/player/palettes/hero_palettes.json", {}).get("checks")
    if chk:
        W("Readability checks (recomputed by every build; CIEDE2000, simulations %s): smallest difference between "
          "two slot defaults over all simulations: loincloth %.1f, loincloth shadow %.1f (a value above about 20 reads "
          "as a clearly different colour). The two light cloths (yellow, blue) and the two dark ones (pink, green) "
          "differ in hue along the blue-yellow axis that red-green dichromats keep, and every pair also differs in "
          "pattern; tags, arrows and eggs use the same split (`mp_indicators.png`)."
          % (", ".join(chk["sims"]), chk["cvd_min_de2000"]["cloth"], chk["cvd_min_de2000"]["cloth_shadow"]))
        W("")
        worst = []
        for b, d in chk["biome_camouflage"].items():
            for n, v in d.items():
                if v >= 0.1:
                    worst.append("%s on %s %.0f %%" % (n, b, 100 * v))
        W("Background camouflage (share of the background pixels behind a standing hero within CIEDE2000 10 of the "
          "loincloth colour): everything under 10 %% except %s. The dark per-slot outline keeps those heroes "
          "readable (`heroes_biomes.png`); green is swapped for white on jungle / swamp arenas."
          % ("; ".join(worst) if worst else "nothing"))
        W("")

    # ------------------------------------------------------------------ 17.2 - 17.5 file tables
    def file_table(title, sections, intro=None):
        ks = [k for sec in sections.split("+") for k in keys(sec)]
        if not ks:
            return
        W(title)
        W("")
        if intro:
            W(intro)
            W("")
        table(["File", "Size", "Frame", "Grid", "Pivot", "Animations", "Use"],
              [[_short(k), _sz(R[k]), _fr(R[k]), _gr(R[k]), _pv(R[k]), _anims(R[k]), R[k].get("note", "")]
               for k in ks])

    file_table("### 17.2 Player sheets", "player",
               "`hero_spear.png` has the layout, animations, pivots and cloth pixels of `hero.png` (section 3); the "
               "spear is a thrown weapon like the axe (release frames bare-handed).")
    file_table("### 17.3 Co-op objects (DESIGN D.5)", "objects")
    file_table("### 17.4 Items and effects", "items+fx")
    file_table("### 17.5 UI", "ui")

    # ------------------------------------------------------------------ 17.6 art-B hand-over
    kb = keys(None, "art-B")
    W("### 17.6 Worlds and creatures (art-B hand-over)")
    W("")
    if kb:
        W("Rows handed over by art-B (`.tools/asset_candidates/expansion/_handover/`), checked against the files: "
          "size measured from the PNG, at most 2048 px a side, every source pack credited, CC0. Actor pivots follow "
          "section 1 (`cell_h - 16`); body boxes are art-B's measurements of the first idle frame (suggestions).")
        W("")

        def use(v):
            t = v.get("note") or ""
            if "scroll" in v:
                t += " (scroll %.2f)" % v["scroll"]
            if v.get("tiles") == "TERRAIN_TILES":
                t += "; layout and collision of section 10.1 (40 tiles)"
            if "tiles_inline" in v:
                t += "; tiles: " + "; ".join("%s %s" % kv for kv in v["tiles_inline"].items())
            if "zones_logical" in v:
                t += "; zones (logical px from the feet, facing right): " + "; ".join(
                    "%s %s" % (z, b) for z, b in v["zones_logical"].items())
            return t
        table(["File", "Size", "Frame", "Grid", "Pivot", "Facing", "Body box (logical)", "Animations", "Use"],
              [[_short(k), _sz(R[k]), _fr(R[k]), _gr(R[k]), _pv(R[k]), R[k].get("facing", "-"),
                "%dx%d" % tuple(R[k]["body_box_logical"]) if "body_box_logical" in R[k] else "-", _anims(R[k]),
                use(R[k])] for k in kb])
        notes = extra.get("handover_notes", [])
        if notes:
            W("Notes from the hand-over (art-B's words, kept here because the staging folder is not versioned):")
            W("")
            out.extend(notes)
            W("")
    else:
        W("(none yet)")
        W("")

    # ------------------------------------------------------------------ 17.7 edit log
    W("### 17.7 Edit log (2.0)")
    W("")
    table(["File", "Owner", "Source", "Edits"],
          [[_short(k), R[k].get("owner", "art-A"), R[k].get("source", "-"), R[k].get("edits", "-")]
           for k in sorted(R)])

    # ------------------------------------------------------------------ 17.8 sources
    W("### 17.8 Sources and licences (2.0)")
    W("")
    packs = extra.get("packs", {})
    W("All CC0 1.0 (tier A); no CC-BY, share-alike or non-commercial file (DESIGN F.3). Shipped 1.0 files that are "
      "recoloured or composited keep their original source (section 15). Licence texts: `assets/licenses/`; "
      "credits: `CREDITS.md`.")
    W("")
    table(["Pack", "Author", "Licence", "Licence file", "2.0 files"],
          [[p["title"], p["author"], p["license"], "`%s`" % p["file"], p["count"]] for p in packs.values()])

    # ------------------------------------------------------------------ 17.9 gaps
    W("### 17.9 Known gaps (2.0, art-A)")
    W("")
    for g in extra.get("gaps", []):
        W("- " + g)
    W("")
    W(END)
    return out


def replace_in(path, lines):
    """put the section into the manifest: replace the marked block, or append it"""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    block = "\n".join(lines)
    if BEGIN in text and END in text:
        a = text.index(BEGIN)
        b = text.index(END) + len(END)
        text = text[:a] + block + text[b:]
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
