"""Writes tools/autoplay/g3_versus.flow: every (arena, mode) cell CPUs play, through the real versus UI (G3).

The generator of the versioned flow: integration's of G3b without its one special case (a human walking into the
open on Colossus Hall) - since ruling R8 / G78 (the hard cap of a Last Caveman Standing round) two idle humans end
every cell. Versioned by the G3c integration; run it after an arena file gains or loses a mode:
    python tools/autoplay/gen_versus_flow.py
"""
import re, os, glob

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODES = ["grub_stack", "last_caveman", "hot_rock", "clubball"]
MODE_TITLE = {"grub_stack": "Grub Stack", "last_caveman": "Last Caveman Standing", "hot_rock": "Hot Rock",
              "clubball": "Clubball"}

arenas = []
for path in sorted(glob.glob(os.path.join(ROOT, "levels", "arena_*.lvl"))):
    text = open(path, encoding="utf-8").read()
    aid = os.path.basename(path)[:-4]
    modes = re.search(r"(?m)^modes\s*=\s*(.*)$", text).group(1).replace(" ", "").split(",")
    players = int(re.search(r"(?m)^players\s*=\s*(\d+)", text).group(1))
    bots_m = re.search(r"(?m)^bots\s*=\s*(.*)$", text)
    bots = modes if bots_m is None else ([] if bots_m.group(1).strip() == "none" else bots_m.group(1).replace(" ", "").split(","))
    arenas.append((aid, modes, players, bots))

out = []
w = out.append
w("# Gate G3 (docs/expansion/PLAN.md 6.2: \"every (arena, mode) bot test green\"; the orchestrator's G3 task: \"every versus")
w("# mode on every arena with bots - windowed, screenshots looked at\"): versus through the real UI on EVERY (arena, mode)")
w("# cell CPUs play - title -> Play -> Versus -> the lobby (P1 presses Jump on the left keyboard half, P2 on the numpad;")
w("# two CPU seats as Hunters) -> the rules (the mode; first to 1 round win) -> the arena select -> the round -> the")
w("# results -> the lobby, cell after cell, then the title. A humans-only cell (G50, meta `bots`) is not offered with CPUs")
w("# seated and is left out (Tar Pulleys' Last Caveman Standing). The humans press nothing during the rounds (their")
w("# heroes read the keyboard halves), in EVERY cell: two campers no sudden death reaches (Colossus Hall's ledges hide")
w("# them from the stalactites; such a round ran 29 400 ticks at G3b) end with the hard cap of ruling R8 / G78 - 60 s")
w("# after the sudden death started the hero with fewer hurts wins, else the round is a draw and the next one starts")
w("# (tests/test_versus_rules.gd plays the idle rounds). The Hunters are core-B's HeroBots on DA's graphs. Screenshots: rules, arena card,")
w("# intro, every 480 ticks, results of every cell. Generated by tools/autoplay/gen_versus_flow.py from levels/arena_*.lvl -")
w("# run it again whenever an arena's `modes` / `bots` change (cells and card positions follow; the arena select lists")
w("# Random, the open arenas of the mode in file order, Party Mix; it opens on the match's arena). Owner: integration.")
w("#   GD_TIMEOUT=5400 bash .tools/gd.sh play --flow=tools/autoplay/g3_versus.flow --fast --fresh-user --out=g3_versus")
w("# Headless (no screenshots):")
w("#   GD_TIMEOUT=5400 bash .tools/gd.sh script res://scripts/core/dev/headless_flow.gd -- \\")
w("#       --flow=tools/autoplay/g3_versus.flow --fast --fresh-user --user-dir=res://build/flow_user_g3_versus")
w("# --- Boot, title, Play > Versus, seats -----------------------------------------------------------------------------")
for line in """wait_until flow.current_screen == title 600
wait_until flow.busy == false 600
wait 40
press ui_accept
wait 10
press ui_down
press ui_down
wait 6
press ui_accept
wait_until flow.current_screen == versus_lobby 300
wait_until flow.busy == false 600
wait 10
key Space
key Kp_0
wait 10
expect game.versus_match.get_seat(0).kind == 1
expect game.versus_match.get_seat(1).kind == 1
# The focus starts on START: Up = Teams, Up = card 1, Right twice = the free card 3; confirm on a free card adds a
# Hunter; Right = card 4, confirm = a second Hunter; a card's Up = START.
press ui_up
press ui_up
press ui_right
press ui_right
press ui_accept
wait 4
press ui_right
press ui_accept
wait 10
expect game.versus_match.player_count() == 4
expect game.versus_match.is_bot(2) == true
expect game.versus_match.is_bot(3) == true
press ui_up
wait 6
shot lobby_two_hunters""".split("\n"):
    w(line)

cur_mode = 0
cur_arena = "random"
first = True
n = 0
for mi, mode in enumerate(MODES):
    cards = ["random"] + [a for a, modes, players, bots in arenas if mode in modes and players >= 4] + ["party_mix"]
    cells = [a for a, modes, players, bots in arenas if mode in modes and players >= 4 and mode in bots]
    for arena in cells:
        n += 1
        short = arena[len("arena_"):]
        w("")
        w("# --- Cell %d: %s on %s %s" % (n, MODE_TITLE[mode], short, "-" * max(1, 80 - len(MODE_TITLE[mode]) - len(short))))
        if not first:
            w("# From the results: Right + confirm = the lobby (seats kept); both humans ready again, START.")
            w("press ui_right")
            w("press ui_accept")
            w("wait_until flow.current_screen == versus_lobby 600")
            w("wait_until flow.busy == false 600")
            w("wait 20")
        w("hold Ctrl Kp_Enter")
        w("wait_until game.versus_match.can_start() == true 600")
        w("release all")
        w("wait 10")
        w("press ui_accept")
        w("wait_until flow.current_screen == versus_rules 300")
        w("wait_until flow.busy == false 600")
        w("wait 10")
        for _ in range(mi - cur_mode):
            w("press ui_right")
            w("wait 4")
        cur_mode = mi
        w("expect game.versus_match.mode == %d" % mi)
        if first:
            w("# Down twice = Rounds; Right = first to 1 round win (a short match per cell); back up to the Mode row.")
            w("press ui_down")
            w("press ui_down")
            w("press ui_right")
            w("wait 4")
            w("expect game.versus_match.rounds_to_win == 1")
            w("press ui_up")
            w("press ui_up")
        w("wait 6")
        w("shot rules_%s_%s" % (mode, short))
        w("# Up from the Mode row: \"Choose the arena\".")
        w("press ui_up")
        w("press ui_accept")
        w("wait_until flow.current_screen == versus_arena 300")
        w("wait_until flow.busy == false 600")
        w("wait 10")
        at = cards.index(cur_arena) if cur_arena in cards else 0
        to = cards.index(arena)
        for _ in range(abs(to - at)):
            w("press ui_right" if to > at else "press ui_left")
            w("wait 4")
        cur_arena = arena
        w("expect game.versus_match.arena == %s" % arena)
        w("shot arena_%s_%s" % (mode, short))
        w("press ui_accept")
        w("wait_until flow.current_screen == level 900")
        w("wait_until flow.busy == false 600")
        w("wait_until level.level_id == %s 600" % arena)
        w("expect game.mode == 2")
        w("expect level.hero_count() == 4")
        w("input device")
        w("wait 2")
        w("shot %s_%s_intro" % (mode, short))
        w("every 480 %s_%s" % (mode, short))
        w("wait_until flow.current_screen == versus_results 30000")
        w("every 0")
        w("wait_until flow.busy == false 600")
        w("wait 90")
        w("# The results take a confirm only 0.8 s after they opened (VersusResultsScreen.ACCEPT_GRACE, real time): a")
        w("# headless run renders 90 frames faster than that, so wait by the clock as well.")
        w("wait_ms 1000")
        w("shot results_%s_%s" % (mode, short))
        w("expect game.versus_match.is_over() == true")
        w("expect game.versus_match.mode == %d" % mi)
        first = False

w("")
w("# --- Back to the lobby and the title ------------------------------------------------------------------------------")
for line in """press ui_right
press ui_accept
wait_until flow.current_screen == versus_lobby 600
wait_until flow.busy == false 600
wait 20
press ui_cancel
wait_until flow.current_screen == title 600
wait_until flow.busy == false 600
wait 20
shot title_again""".split("\n"):
    w(line)
open(os.path.join(ROOT, "tools", "autoplay", "g3_versus.flow"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("cells", n)
