"""Writes tools/autoplay/g3_versus.flow: every (arena, mode) cell CPUs play, through the real versus UI (G3).

The generator of the versioned flow: integration's of G3b without its one special case (a human walking into the
open on Colossus Hall) - since ruling R8 / G78 (the hard cap of a Last Caveman Standing round) two idle humans end
every cell. Versioned by the G3c integration; run it after an arena file gains or loses a mode:
    python tools/autoplay/gen_versus_flow.py

With --perf[=<file>] it writes a second flow instead (default build/versus/versus_perf.flow; phase 4, PLAN.md 7 P4.2:
"--perf ... 4-player arenas"): ONE 4-hero round per arena for the game's own performance probe - P1 a human who
presses nothing, three Hunter CPUs (the most bot work a real match has), Grub Stack where the arena has it (a clocked
round: 2 185 ticks, the same length everywhere), else the first mode CPUs play there (Coconut Cove: Clubball), no
screenshots. Play it windowed with the probe and read the `Perf: level:<arena>` lines (tick cost per arena):
    python tools/autoplay/gen_versus_flow.py --perf
    GD_TIMEOUT=3000 bash .tools/gd.sh play --flow=build/versus/versus_perf.flow --fresh-user --perf --out=versus_perf
(add --fast for one tick per frame: the tick costs are the same, the run takes minutes instead of a quarter hour).
"""
import re, os, glob, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODES = ["grub_stack", "last_caveman", "hot_rock", "clubball"]
MODE_TITLE = {"grub_stack": "Grub Stack", "last_caveman": "Last Caveman Standing", "hot_rock": "Hot Rock",
              "clubball": "Clubball"}

arenas = []
for path in sorted(glob.glob(os.path.join(ROOT, "levels", "arena_*.lvl"))):
    text = open(path, encoding="utf-8").read()
    aid = os.path.basename(path)[:-4]
    modes = re.search(r"(?m)^modes\s*=\s*(.*)$", text).group(1).replace(" ", "").split(",")
    players = int(re.search(r"(?m)^players\s*=\s*(\d+)", text).group(1))
    bots_m = re.search(r"(?m)^bots\s*=\s*(.*)$", text)
    bots = modes if bots_m is None else ([] if bots_m.group(1).strip() == "none" else bots_m.group(1).replace(" ", "").split(","))
    arenas.append((aid, modes, players, bots))

def perf_flow(path):
    """One 4-hero round per arena for --perf: a human who presses nothing and three Hunters (see the header)."""
    out = []
    w = out.append
    w("# Phase 4 (docs/expansion/PLAN.md 7 P4.2): the tick cost of a 4-hero versus round on EVERY arena, for the game's own")
    w("# performance probe (--perf, scripts/core/dev/perf_probe.gd; budget: docs/ARCHITECTURE.md 11). Through the real")
    w("# versus UI: P1 joins on the left keyboard half and presses nothing in the rounds, three CPU seats as Hunters -")
    w("# the most bot work a real match has. One round per arena (first to 1 round win): Grub Stack where the arena has")
    w("# it (clocked: 2 185 ticks with four players), else the first mode CPUs play there. No screenshots. Generated by")
    w("# tools/autoplay/gen_versus_flow.py --perf from levels/arena_*.lvl; owner: versus.")
    w("#   GD_TIMEOUT=3000 bash .tools/gd.sh play --flow=%s --fresh-user --perf --out=versus_perf" % path)
    w("# (add --fast for one tick per rendered frame). Read the `Perf: level:<arena>` lines and <out>/perf.json.")
    for line in """wait_until flow.current_screen == title 600
wait_until flow.busy == false 600
wait 40
press ui_accept
wait 10
press ui_down
press ui_down
wait 6
press ui_accept
wait_until flow.current_screen == versus_lobby 300
wait_until flow.busy == false 600
wait 10
key Space
wait 10
expect game.versus_match.get_seat(0).kind == 1
# The focus starts on START: Up = Teams, Up = card 1; Right = the free card 2, confirm adds a Hunter; the same for
# cards 3 and 4; a card's Up = START.
press ui_up
press ui_up
press ui_right
press ui_accept
wait 4
press ui_right
press ui_accept
wait 4
press ui_right
press ui_accept
wait 10
expect game.versus_match.player_count() == 4
expect game.versus_match.human_count() == 1
expect game.versus_match.is_bot(1) == true
expect game.versus_match.is_bot(2) == true
expect game.versus_match.is_bot(3) == true
press ui_up
wait 6""".split("\n"):
        w(line)
    cells = []
    for aid, modes, players, bots in arenas:
        playable = [m for m in MODES if m in modes and m in bots]
        if players >= 4 and playable:
            cells.append((MODES.index("grub_stack" if "grub_stack" in playable else playable[0]), aid))
    cells.sort()
    cur_mode = 0
    cur_arena = "random"
    first = True
    for mi, arena in cells:
        mode = MODES[mi]
        cards = ["random"] + [a for a, modes, players, bots in arenas if mode in modes and players >= 4] + ["party_mix"]
        short = arena[len("arena_"):]
        w("")
        w("# --- %s on %s %s" % (MODE_TITLE[mode], short, "-" * max(1, 90 - len(MODE_TITLE[mode]) - len(short))))
        if not first:
            w("press ui_right")
            w("press ui_accept")
            w("wait_until flow.current_screen == versus_lobby 600")
            w("wait_until flow.busy == false 600")
            w("wait 20")
        w("hold Ctrl")
        w("wait_until game.versus_match.can_start() == true 600")
        w("release all")
        w("wait 10")
        w("press ui_accept")
        w("wait_until flow.current_screen == versus_rules 300")
        w("wait_until flow.busy == false 600")
        w("wait 10")
        for _ in range(mi - cur_mode):
            w("press ui_right")
            w("wait 4")
        if mi != cur_mode:
            cur_arena = "random"
        cur_mode = mi
        w("expect game.versus_match.mode == %d" % mi)
        if first:
            w("press ui_down")
            w("press ui_down")
            w("press ui_right")
            w("wait 4")
            w("expect game.versus_match.rounds_to_win == 1")
            w("press ui_up")
            w("press ui_up")
        w("wait 6")
        w("press ui_up")
        w("press ui_accept")
        w("wait_until flow.current_screen == versus_arena 300")
        w("wait_until flow.busy == false 600")
        w("wait 10")
        at = cards.index(cur_arena) if cur_arena in cards else 0
        to = cards.index(arena)
        for _ in range(abs(to - at)):
            w("press ui_right" if to > at else "press ui_left")
            w("wait 4")
        cur_arena = arena
        w("expect game.versus_match.arena == %s" % arena)
        w("press ui_accept")
        w("wait_until flow.current_screen == level 900")
        w("wait_until flow.busy == false 600")
        w("wait_until level.level_id == %s 600" % arena)
        w("expect game.mode == 2")
        w("expect level.hero_count() == 4")
        w("input device")
        w("wait_until flow.current_screen == versus_results 40000")
        w("wait_until flow.busy == false 600")
        w("wait 90")
        w("wait_ms 1000")
        w("expect game.versus_match.is_over() == true")
        first = False
    w("")
    for line in """press ui_right
press ui_accept
wait_until flow.current_screen == versus_lobby 600
wait_until flow.busy == false 600
wait 20
press ui_cancel
wait_until flow.current_screen == title 600
wait_until flow.busy == false 600
wait 20""".split("\n"):
        w(line)
    target = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    open(target, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("perf cells", len(cells), "->", path)


for arg in sys.argv[1:]:
    if arg == "--perf" or arg.startswith("--perf="):
        perf_flow(arg[len("--perf="):] if arg.startswith("--perf=") else "build/versus/versus_perf.flow")
        sys.exit(0)


out = []
w = out.append
w("# Gate G3 (docs/expansion/PLAN.md 6.2: \"every (arena, mode) bot test green\"; the orchestrator's G3 task: \"every versus")
w("# mode on every arena with bots - windowed, screenshots looked at\"): versus through the real UI on EVERY (arena, mode)")
w("# cell CPUs play - title -> Play -> Versus -> the lobby (P1 presses Jump on the left keyboard half, P2 on the numpad;")
w("# two CPU seats as Hunters) -> the rules (the mode; first to 1 round win) -> the arena select -> the round -> the")
w("# results -> the lobby, cell after cell, then the title. A humans-only cell (G50, meta `bots`) is not offered with CPUs")
w("# seated and is left out (Tar Pulleys' Last Caveman Standing). The humans press nothing during the rounds (their")
w("# heroes read the keyboard halves), in EVERY cell: two campers no sudden death reaches (Colossus Hall's ledges hide")
w("# them from the stalactites; such a round ran 29 400 ticks at G3b) end with the hard cap of ruling R8 / G78 - 60 s")
w("# after the sudden death started the hero with fewer hurts wins, else the round is a draw and the next one starts")
w("# (tests/test_versus_rules.gd plays the idle rounds). The Hunters are core-B's HeroBots on DA's graphs. Screenshots: rules, arena card,")
w("# intro, every 480 ticks, results of every cell. Generated by tools/autoplay/gen_versus_flow.py from levels/arena_*.lvl -")
w("# run it again whenever an arena's `modes` / `bots` change (cells and card positions follow; the arena select lists")
w("# Random, the open arenas of the mode in file order, Party Mix; it opens on the match's arena). Owner: integration.")
w("#   GD_TIMEOUT=5400 bash .tools/gd.sh play --flow=tools/autoplay/g3_versus.flow --fast --fresh-user --out=g3_versus")
w("# Headless (no screenshots):")
w("#   GD_TIMEOUT=5400 bash .tools/gd.sh script res://scripts/core/dev/headless_flow.gd -- \\")
w("#       --flow=tools/autoplay/g3_versus.flow --fast --fresh-user --user-dir=res://build/flow_user_g3_versus")
w("# --- Boot, title, Play > Versus, seats -----------------------------------------------------------------------------")
for line in """wait_until flow.current_screen == title 600
wait_until flow.busy == false 600
wait 40
press ui_accept
wait 10
press ui_down
press ui_down
wait 6
press ui_accept
wait_until flow.current_screen == versus_lobby 300
wait_until flow.busy == false 600
wait 10
key Space
key Kp_0
wait 10
expect game.versus_match.get_seat(0).kind == 1
expect game.versus_match.get_seat(1).kind == 1
# The focus starts on START: Up = Teams, Up = card 1, Right twice = the free card 3; confirm on a free card adds a
# Hunter; Right = card 4, confirm = a second Hunter; a card's Up = START.
press ui_up
press ui_up
press ui_right
press ui_right
press ui_accept
wait 4
press ui_right
press ui_accept
wait 10
expect game.versus_match.player_count() == 4
expect game.versus_match.is_bot(2) == true
expect game.versus_match.is_bot(3) == true
press ui_up
wait 6
shot lobby_two_hunters""".split("\n"):
    w(line)

cur_mode = 0
cur_arena = "random"
first = True
n = 0
for mi, mode in enumerate(MODES):
    cards = ["random"] + [a for a, modes, players, bots in arenas if mode in modes and players >= 4] + ["party_mix"]
    cells = [a for a, modes, players, bots in arenas if mode in modes and players >= 4 and mode in bots]
    for arena in cells:
        n += 1
        short = arena[len("arena_"):]
        w("")
        w("# --- Cell %d: %s on %s %s" % (n, MODE_TITLE[mode], short, "-" * max(1, 80 - len(MODE_TITLE[mode]) - len(short))))
        if not first:
            w("# From the results: Right + confirm = the lobby (seats kept); both humans ready again, START.")
            w("press ui_right")
            w("press ui_accept")
            w("wait_until flow.current_screen == versus_lobby 600")
            w("wait_until flow.busy == false 600")
            w("wait 20")
        w("hold Ctrl Kp_Enter")
        w("wait_until game.versus_match.can_start() == true 600")
        w("release all")
        w("wait 10")
        w("press ui_accept")
        w("wait_until flow.current_screen == versus_rules 300")
        w("wait_until flow.busy == false 600")
        w("wait 10")
        for _ in range(mi - cur_mode):
            w("press ui_right")
            w("wait 4")
        cur_mode = mi
        w("expect game.versus_match.mode == %d" % mi)
        if first:
            w("# Down twice = Rounds; Right = first to 1 round win (a short match per cell); back up to the Mode row.")
            w("press ui_down")
            w("press ui_down")
            w("press ui_right")
            w("wait 4")
            w("expect game.versus_match.rounds_to_win == 1")
            w("press ui_up")
            w("press ui_up")
        w("wait 6")
        w("shot rules_%s_%s" % (mode, short))
        w("# Up from the Mode row: \"Choose the arena\".")
        w("press ui_up")
        w("press ui_accept")
        w("wait_until flow.current_screen == versus_arena 300")
        w("wait_until flow.busy == false 600")
        w("wait 10")
        at = cards.index(cur_arena) if cur_arena in cards else 0
        to = cards.index(arena)
        for _ in range(abs(to - at)):
            w("press ui_right" if to > at else "press ui_left")
            w("wait 4")
        cur_arena = arena
        w("expect game.versus_match.arena == %s" % arena)
        w("shot arena_%s_%s" % (mode, short))
        w("press ui_accept")
        w("wait_until flow.current_screen == level 900")
        w("wait_until flow.busy == false 600")
        w("wait_until level.level_id == %s 600" % arena)
        w("expect game.mode == 2")
        w("expect level.hero_count() == 4")
        w("input device")
        w("wait 2")
        w("shot %s_%s_intro" % (mode, short))
        w("every 480 %s_%s" % (mode, short))
        w("wait_until flow.current_screen == versus_results 30000")
        w("every 0")
        w("wait_until flow.busy == false 600")
        w("wait 90")
        w("# The results take a confirm only 0.8 s after they opened (VersusResultsScreen.ACCEPT_GRACE, real time): a")
        w("# headless run renders 90 frames faster than that, so wait by the clock as well.")
        w("wait_ms 1000")
        w("shot results_%s_%s" % (mode, short))
        w("expect game.versus_match.is_over() == true")
        w("expect game.versus_match.mode == %d" % mi)
        first = False

w("")
w("# --- Back to the lobby and the title ------------------------------------------------------------------------------")
for line in """press ui_right
press ui_accept
wait_until flow.current_screen == versus_lobby 600
wait_until flow.busy == false 600
wait 20
press ui_cancel
wait_until flow.current_screen == title 600
wait_until flow.busy == false 600
wait 20
shot title_again""".split("\n"):
    w(line)
open(os.path.join(ROOT, "tools", "autoplay", "g3_versus.flow"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("cells", n)
