; Club & Grub - Windows installer (Inno Setup 7). Build it with tools/build_installer.ps1, which passes the version
; from project.godot and checks the result; compiling by hand works too:
;   .tools\innosetup\ISCC.exe /DAppVersion=1.0.0 installer\club_and_grub.iss
; Input: the release export in build\windows (tools/build_windows.ps1). Output: build\ClubAndGrub-<version>-setup.exe
;
; Installs per user by default (no administrator rights, %LOCALAPPDATA%\Programs); the first page offers an
; all-users install. Saved games and settings live in %APPDATA%\ClubAndGrub and are kept on uninstall unless the
; player asks to delete them. The installer art is generated by tools/make_installer_art.py.

#ifndef AppVersion
  #define AppVersion "1.0.0"
#endif
#define AppName "Club & Grub"
#define AppExe "ClubAndGrub.exe"
#define AppPublisher "Club & Grub Team"
#define AppUrl "https://github.com/brunolau/grub-game"
#define UserDataDir "ClubAndGrub"

[Setup]
; Never change AppId: it ties upgrades and the uninstaller to earlier installs.
AppId={{1BE32CEC-8418-43E5-BEDD-2F34A2D0439C}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppUrl}
AppSupportURL={#AppUrl}/issues
AppUpdatesURL={#AppUrl}/releases
AppCopyright=Copyright (C) 2026 {#AppPublisher}
VersionInfoVersion={#AppVersion}.0
VersionInfoProductName={#AppName}
VersionInfoDescription={#AppName} Setup
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog commandline
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; Windows 10 or newer (the game needs OpenGL 3.3).
MinVersion=10.0
OutputDir=..\build
OutputBaseFilename=ClubAndGrub-{#AppVersion}-setup
SetupIconFile=club_and_grub.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
WizardStyle=modern dynamic
WizardImageFile=wizard_large_1x.png,wizard_large_2x.png,wizard_large_3x.png
WizardSmallImageFile=wizard_small_1x.png,wizard_small_2x.png,wizard_small_3x.png
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes
CloseApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\build\windows\{#AppExe}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\licenses\*"; DestDir: "{app}\licenses"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExe}"
Name: "{group}\Licences and credits"; Filename: "{app}\licenses"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Run]
; "&&" shows one ampersand on the check box (a single one would underline the next letter).
Filename: "{app}\{#AppExe}"; Description: "Launch Club && Grub"; Flags: nowait postinstall skipifsilent

[Code]
// Saved games and settings are not part of the installation: offer to delete them after an interactive uninstall.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  if CurUninstallStep <> usPostUninstall then
    Exit;
  DataDir := ExpandConstant('{userappdata}\{#UserDataDir}');
  if UninstallSilent or not DirExists(DataDir) then
    Exit;
  if MsgBox('Also delete your saved games and settings?' + #13#10 + DataDir, mbConfirmation,
      MB_YESNO or MB_DEFBUTTON2) = IDYES then
    DelTree(DataDir, True, True, True);
end;
