; Club & Grub - Windows installer (Inno Setup 7). Build it with tools/build_installer.ps1, which passes the version
; from project.godot and checks the result; compiling by hand works too:
;   .tools\innosetup\ISCC.exe /DAppVersion=2.0.0 installer\club_and_grub.iss
; Input: the release export in build\windows (tools/build_windows.ps1). Output: build\ClubAndGrub-<version>-setup.exe
;
; Installs per user by default (no administrator rights, %LOCALAPPDATA%\Programs); the first page offers an
; all-users install. Saved games and settings live in %APPDATA%\ClubAndGrub and are kept on uninstall unless the
; player asks to delete them. The installer art is generated by tools/make_installer_art.py.
;
; Upgrades: the AppId below is the one 1.0.0 was installed with, so the 2.0.0 setup replaces a 1.0.0 installation in
; place (same folder, same Start menu entry, one entry under Settings > Apps). The saves are not part of the
; installation and are not touched by the installer; the game migrates a 1.0 save itself and keeps the 1.0 file as
; %APPDATA%\ClubAndGrub\save.v1.json.
;
; Defines (ISCC /D<name>=<value>):
;   AppVersion   the version shown and packed (default below)
;   BuildDir     folder with ClubAndGrub.exe and licenses\ (default ..\build\windows)
;   OutputDir    folder the setup exe is written to (default ..\build)
;   TestAppId    TEST MODE of tools/build_installer.ps1 -TestInstall: a throwaway GUID (no braces). The installer
;                compiled with it is a different application for Windows - its own AppId, its own name, Start menu
;                group and uninstall entry, no desktop shortcut, no "close the running game", no question about
;                saved games - so installing and uninstalling it can never touch a real installation of the game,
;                its Start menu entry or its saves. It is named ...-setup-TEST-ONLY.exe; never publish it.

#ifndef AppVersion
  #define AppVersion "2.0.0"
#endif
#ifndef BuildDir
  #define BuildDir "..\build\windows"
#endif
#ifndef OutputDir
  #define OutputDir "..\build"
#endif
#define AppExe "ClubAndGrub.exe"
#define AppPublisher "Club & Grub Team"
#define AppUrl "https://github.com/brunolau/grub-game"
#define UserDataDir "ClubAndGrub"
#ifdef TestAppId
  #define AppName "Club & Grub installer test " + Copy(TestAppId, 1, 8)
  #define SetupAppId "{{" + TestAppId + "}"
  #define SetupBaseName "ClubAndGrub-" + AppVersion + "-setup-TEST-ONLY"
#else
  #define AppName "Club & Grub"
  ; Never change this AppId: it ties upgrades and the uninstaller to earlier installs (1.0.0 and later).
  #define SetupAppId "{{1BE32CEC-8418-43E5-BEDD-2F34A2D0439C}"
  #define SetupBaseName "ClubAndGrub-" + AppVersion + "-setup"
#endif

[Setup]
AppId={#SetupAppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppUrl}
AppSupportURL={#AppUrl}/issues
AppUpdatesURL={#AppUrl}/releases
AppCopyright=Copyright (C) 2026 {#AppPublisher}
VersionInfoVersion={#AppVersion}.0
VersionInfoProductName={#AppName}
VersionInfoDescription={#AppName} Setup
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog commandline
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; Windows 10 or newer (the game needs OpenGL 3.3).
MinVersion=10.0
OutputDir={#OutputDir}
OutputBaseFilename={#SetupBaseName}
SetupIconFile=club_and_grub.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
WizardStyle=modern dynamic
WizardImageFile=wizard_large_1x.png,wizard_large_2x.png,wizard_large_3x.png
WizardSmallImageFile=wizard_small_1x.png,wizard_small_2x.png,wizard_small_3x.png
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes
#ifdef TestAppId
; The test installer never closes a running program: a real copy of the game may be running.
CloseApplications=no
#else
CloseApplications=yes
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

#ifndef TestAppId
[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
#endif

[Files]
Source: "{#BuildDir}\{#AppExe}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}\licenses\*"; DestDir: "{app}\licenses"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExe}"
Name: "{group}\Licences and credits"; Filename: "{app}\licenses"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
#ifndef TestAppId
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon
#endif

[Run]
; "&&" shows one ampersand on the check box (a single one would underline the next letter).
Filename: "{app}\{#AppExe}"; Description: "Launch Club && Grub"; Flags: nowait postinstall skipifsilent

#ifndef TestAppId
[Code]
// Saved games and settings are not part of the installation: offer to delete them after an interactive uninstall.
// (Not compiled into the test installer: it holds no code that could delete a player's saves.)
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  if CurUninstallStep <> usPostUninstall then
    Exit;
  DataDir := ExpandConstant('{userappdata}\{#UserDataDir}');
  if UninstallSilent or not DirExists(DataDir) then
    Exit;
  if MsgBox('Also delete your saved games and settings?' + #13#10 + DataDir, mbConfirmation,
      MB_YESNO or MB_DEFBUTTON2) = IDYES then
    DelTree(DataDir, True, True, True);
end;
#endif
